export default function () {
  return {
    status: '',
    token: localStorage.getItem('tokenelec') || '',
    user : {},
    pedido:[],
    boolusuario:false,
    booledituser:false,
    boolpuntos:false,
    boolgeneral:false,
    boolmtto:false,
    booldistrito:false,
    booldenuncia:false,
    boolreporte:false,
    boolcronograma:false,
    booltecnico:false,
    booljunta:false,
    boolgestionar:false,
    boolreclamo:false,
    boolalmacen:false,
    booldependencia:false,
    boolreporte2:false,
    boolveracta:false,
    boolregacta:false,
    booleditacta:false,
    boolagenda:false,
    boolreportemat:false,
    booldelposte:false,
    // boolnatural:false,
    // booldemandado:false,
    // boolcotizacion:false,
    // boolmicotizacion:false,
    // inventario:false,
    // ventadetalle:false,
    // historialventadetalle:false,
    // ventalocal:false,
    // historialventalocal:false,
    // empleados:false,
    // reportes:false,
    // gastos:false,
    // historialprestamo:false,
  }
}
